build:
	g++ -std=c++17 -c ./src/*.cpp
	mkdir -p obj && mv ./*.o ./obj
	g++ ./obj/*.o -o main
gui: ./src/*.cpp
	g++ -std=c++17 -c ./src/*.cpp -I/Users/reguly/Work/software/SFML-install/include -DGRAPHICS
	mkdir -p obj && mv ./*.o ./obj
	g++ ./obj/*.o -o gui -L/Users/reguly/Work/software/SFML-install/lib -F/Users/reguly/Work/software/SFML-install/lib -lsfml-graphics -lsfml-window -lsfml-system -framework freetype
all: build gui
